import 'package:equatable/equatable.dart';
import 'package:glam/src/features/auth/domain/user.dart';

/// A comment or system event on an issue/MR (`/:id/notes`).
class Note extends Equatable {
  const Note({
    required this.id,
    required this.body,
    this.author,
    this.createdAt,
    this.updatedAt,
    this.system = false,
    this.resolvable = false,
    this.resolved = false,
    this.confidential = false,
  });

  factory Note.fromJson(Map<String, dynamic> json) {
    return Note(
      id: json['id'] as int? ?? 0,
      body: json['body'] as String? ?? '',
      author: json['author'] is Map<String, dynamic>
          ? GitLabUser.fromJson(json['author'] as Map<String, dynamic>)
          : null,
      createdAt: _date(json['created_at']),
      updatedAt: _date(json['updated_at']),
      system: json['system'] as bool? ?? false,
      resolvable: json['resolvable'] as bool? ?? false,
      resolved: json['resolved'] as bool? ?? false,
      confidential: json['confidential'] as bool? ?? false,
    );
  }

  final int id;
  final String body;
  final GitLabUser? author;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  /// System notes are generated by events ("closed via commit x").
  final bool system;
  final bool resolvable;
  final bool resolved;
  final bool confidential;

  static DateTime? _date(Object? v) =>
      v is String ? DateTime.tryParse(v)?.toLocal() : null;

  @override
  List<Object?> get props => [id, body];
}
